#!/usr/bin/env bash
# Mavjud Odoo o'rnatma uchun GitHub auto-deploy integratsiyasi.
# Bu skript Odoo'ni o'rnatmaydi — u allaqachon /root/odoo/ da ishlayotgan bo'lishi kerak.
#
# Foydalanish:
#   curl -fsSL https://raw.githubusercontent.com/USER/REPO/main/deploy/setup.sh | bash -s -- https://github.com/USER/REPO.git
# Yoki repo allaqachon klon qilingan bo'lsa:
#   cd /opt/odoo-vps && bash deploy/setup.sh
set -euo pipefail

REPO_URL="${1:-${REPO_URL:-}}"
REPO_DIR="${REPO_DIR:-/opt/odoo-vps}"
EXISTING_ODOO_DIR="${EXISTING_ODOO_DIR:-/root/odoo}"
BRANCH="${DEPLOY_BRANCH:-main}"
WEBHOOK_PORT="${WEBHOOK_PORT:-9000}"

log()  { echo -e "\033[1;32m[setup]\033[0m $*"; }
err()  { echo -e "\033[1;31m[setup]\033[0m $*" >&2; }
warn() { echo -e "\033[1;33m[setup]\033[0m $*"; }

if [ "$EUID" -ne 0 ]; then
  err "Bu skriptni root sifatida ishga tushiring (sudo)."
  exit 1
fi

# === 1. Mavjud Odoo'ni tekshirish ===
if [ ! -f "$EXISTING_ODOO_DIR/docker-compose.yml" ]; then
  err "Mavjud Odoo topilmadi: $EXISTING_ODOO_DIR/docker-compose.yml"
  err "Bu skript faqat sizda allaqachon ishlayotgan Odoo bo'lsa ishlaydi."
  exit 1
fi
log "Mavjud Odoo topildi: $EXISTING_ODOO_DIR"

# === 2. Backup ===
BACKUP_DIR="/root/odoo-backup-$(date +%Y%m%d-%H%M%S)"
log "Mavjud setup backup qilinmoqda: $BACKUP_DIR"
cp -a "$EXISTING_ODOO_DIR" "$BACKUP_DIR"
log "Backup tayyor (xavfsizlik uchun saqlang)"

# === 3. Kerakli paketlar ===
log "Kerakli paketlar tekshirilmoqda..."
apt-get update -y -qq
apt-get install -y --no-install-recommends git rsync python3 ufw curl ca-certificates >/dev/null

# === 4. Repo'ni klon qilish ===
if [ -d "$REPO_DIR/.git" ]; then
  log "Repo allaqachon mavjud: $REPO_DIR — yangilanmoqda"
  git -C "$REPO_DIR" fetch origin "$BRANCH"
  git -C "$REPO_DIR" reset --hard "origin/$BRANCH"
else
  if [ -z "$REPO_URL" ]; then
    err "REPO_URL berilmagan."
    err "Foydalanish: bash setup.sh https://github.com/USER/REPO.git"
    exit 1
  fi
  log "Repo klonlanmoqda: $REPO_URL -> $REPO_DIR"
  mkdir -p "$(dirname "$REPO_DIR")"
  git clone --branch "$BRANCH" "$REPO_URL" "$REPO_DIR"
fi

cd "$REPO_DIR"

# === 5. .env fayli ===
ENV_FILE="$REPO_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  log "Webhook secret yaratilmoqda..."
  WEBHOOK_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 32)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — bu faylga qo'l urmang
WEBHOOK_SECRET=$WEBHOOK_SECRET
WEBHOOK_PORT=$WEBHOOK_PORT
REPO_DIR=$REPO_DIR
EXISTING_ODOO_DIR=$EXISTING_ODOO_DIR
DEPLOY_BRANCH=$BRANCH
EOF
  chmod 600 "$ENV_FILE"
fi

WEBHOOK_SECRET=$(grep -E '^WEBHOOK_SECRET=' "$ENV_FILE" | cut -d= -f2-)

# === 6. Skriptlarni executable qilish ===
chmod +x "$REPO_DIR/deploy/deploy.sh" "$REPO_DIR/deploy/webhook.py"

# === 7. Birinchi sync (initial deploy) ===
log "Birinchi sync: addons -> $EXISTING_ODOO_DIR/addons/"
EXISTING_ODOO_DIR="$EXISTING_ODOO_DIR" REPO_DIR="$REPO_DIR" bash "$REPO_DIR/deploy/deploy.sh" || warn "Initial deploy ogohlantirish bilan tugadi (normal)"

# === 8. Systemd unit ===
log "Webhook xizmati o'rnatilmoqda..."
cp "$REPO_DIR/deploy/odoo-webhook.service" /etc/systemd/system/odoo-webhook.service
systemctl daemon-reload
systemctl enable odoo-webhook.service
systemctl restart odoo-webhook.service
sleep 2

if systemctl is-active --quiet odoo-webhook.service; then
  log "Webhook xizmati ishlayapti ✓"
else
  err "Webhook xizmati ishga tushmadi!"
  systemctl status odoo-webhook.service --no-pager | head -20
fi

# === 9. Firewall ===
if command -v ufw >/dev/null 2>&1; then
  if ufw status | grep -q "Status: active"; then
    log "UFW: webhook port ochilmoqda ($WEBHOOK_PORT)"
    ufw allow "${WEBHOOK_PORT}/tcp" >/dev/null 2>&1 || true
  else
    warn "UFW yoqilmagan — port to'g'ridan-to'g'ri ochiq"
  fi
fi

# === 10. Yakuniy ma'lumot ===
IP=$(curl -fsS https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')

cat <<EOF

============================================================
✅ Auto-deploy o'rnatildi!

Mavjud Odoo:    https://erp.hayrber.org (yoki http://${IP}:8069)
Backup:         $BACKUP_DIR
Webhook health: http://${IP}:${WEBHOOK_PORT}/health
Webhook URL:    http://${IP}:${WEBHOOK_PORT}/

📌 GitHub'da webhook qo'shing:
   Repo → Settings → Webhooks → Add webhook
   Payload URL:  http://${IP}:${WEBHOOK_PORT}/
   Content type: application/json
   Secret:       $WEBHOOK_SECRET
   Events:       Just the push event

⚠️  Yuqoridagi WEBHOOK_SECRET ni nusxa qiling — GitHub'ga kerak bo'ladi.

📊 Loglar:
   journalctl -fu odoo-webhook
   docker compose -f $EXISTING_ODOO_DIR/docker-compose.yml logs -f web
============================================================
EOF
